/**
 * Generates dist/tokens.css from the built token modules.
 * Run after tsup: "build": "tsup && node scripts/generate-css.mjs"
 */

import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const distDir = resolve(__dirname, '..', 'dist')

// Import built token modules (use file:// URL for Windows compatibility)
const { colors, typography, spacing, radii, shadows, animations } = await import(
  pathToFileURL(resolve(distDir, 'index.mjs')).href
)

// Flatten a nested object into CSS custom properties
// e.g. { background: { primary: '#FAF9F6' } } → '--fh-color-background-primary: #FAF9F6;'
function flatten(obj, prefix, lines = []) {
  for (const [key, value] of Object.entries(obj)) {
    const prop = `${prefix}-${key}`
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      flatten(value, prop, lines)
    } else {
      lines.push(`  ${prop}: ${value};`)
    }
  }
  return lines
}

const lines = []

lines.push('/* Auto-generated by @freehold/design-tokens — do not edit */')
lines.push(':root {')

// Colors
flatten(colors, '--fh-color', lines)

// Typography
flatten(typography.fonts, '--fh-font', lines)
flatten(typography.fontSizes, '--fh-font-size', lines)
flatten(typography.fontWeights, '--fh-font-weight', lines)
flatten(typography.lineHeights, '--fh-line-height', lines)
flatten(typography.letterSpacing, '--fh-letter-spacing', lines)

// Spacing
flatten(spacing, '--fh-spacing', lines)

// Radii
flatten(radii, '--fh-radius', lines)

// Shadows
flatten(shadows, '--fh-shadow', lines)

// Animations
flatten(animations.durations, '--fh-duration', lines)
flatten(animations.easings, '--fh-easing', lines)
flatten(animations.transitions, '--fh-transition', lines)

lines.push('}')
lines.push('')

const css = lines.join('\n')
const outPath = resolve(distDir, 'tokens.css')
writeFileSync(outPath, css, 'utf-8')

console.log(`Generated ${outPath} (${css.length} bytes)`)
